swagger: "2.0"
info:
  description: "API for managing images and submitting forms"
  version: "1.0.0"
  title: "Sample API"
host: "localhost:3000"
basePath: "/"
schemes:
- "http"
paths:
  /images:
    get:
      summary: "Fetches all images"
      description: "Returns a list of images from the MongoDB database."
      responses:
        200:
          description: "A list of images"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Image"
        500:
          description: "Server error"
  /api/submit-form:
    post:
      summary: "Submits a form"
      description: "Submits form data to Web3Forms."
      parameters:
        - in: "body"
          name: "body"
          description: "Form data"
          required: true
          schema:
            $ref: "#/definitions/FormSubmit"
      responses:
        200:
          description: "Form submitted successfully"
        500:
          description: "Error in submitting form"
definitions:
  Image:
    type: "object"
    properties:
      url:
        type: "string"
      description:
        type: "string"
  FormSubmit:
    type: "object"
    properties:
      name:
        type: "string"
      email:
        type: "string"
      message:
        type: "string"
